### PR TITLE
Added pip installation instructions to README.md

### PR DESCRIPTION
**Pull request by dashdanw**

### CODE REVIEW

**Comment by trakBan** [comment]
This installs it but doesn't do anything.
```
[tb@trak ~/Desktop]$ pip install "spongebob-cli @ git+https://github.com/trakBan/spongebob-cli@main"
Defaulting to user installation because normal site-packages is not writeable
Collecting spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main
  Cloning https://github.com/trakBan/spongebob-cli (to revision main) to /tmp/pip-install-rqs643xs/spongebob-cli_4113540ac53e482986526f8b1a7969ab
  Running command git clone --filter=blob:none --quiet https://github.com/trakBan/spongebob-cli /tmp/pip-install-rqs643xs/spongebob-cli_4113540ac53e482986526f8b1a7969ab
  Resolved https://github.com/trakBan/spongebob-cli to commit 12163ce701c4c33a03df46f1f20cf6695dda904b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: prettytable in /usr/lib/python3.10/site-packages/prettytable-3.3.0-py3.10.egg (from spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (3.3.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3.10/site-packages/beautifulsoup4-4.11.1-py3.10.egg (from spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (4.11.1)
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (2.28.1)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3.10/site-packages/soupsieve-2.3.2.post1-py3.10.egg (from beautifulsoup4->spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (2.3.2.post1)
Requirement already satisfied: wcwidth in /usr/lib/python3.10/site-packages/wcwidth-0.2.5-py3.10.egg (from prettytable->spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (0.2.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main) (1.26.12)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
[tb@trak ~/Desktop]$ spongebob-cli
bash: spongebob-cli: command not found
```

**Comment by dashdanw** [comment]
I'm able to install it on a fresh docker instance
```bash
dashdanw@DESKTOP-LU46SCL:~$ docker run -it python bash
root@ea2780667b2b:/# pip install "spongebob-cli @ git+https://github.com/trakBan/spongebob-cli@main"
Collecting spongebob-cli@ git+https://github.com/trakBan/spongebob-cli@main
  Cloning https://github.com/trakBan/spongebob-cli (to revision main) to /tmp/pip-install-aix9a18s/spongebob-cli_f292b47f1dd548319f60206b79289de6
  Running command git clone --filter=blob:none --quiet https://github.com/trakBan/spongebob-cli /tmp/pip-install-aix9a18s/spongebob-cli_f292b47f1dd548319f60206b79289de6
  Resolved https://github.com/trakBan/spongebob-cli to commit 12163ce701c4c33a03df46f1f20cf6695dda904b
  Preparing metadata (setup.py) ... done
Collecting prettytable
  Downloading prettytable-3.6.0-py3-none-any.whl (27 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 9.6 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.2 MB/s eta 0:00:00
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (196 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.8/196.8 kB 7.0 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 8.3 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 10.3 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 13.0 MB/s eta 0:00:00
Building wheels for collected packages: spongebob-cli
  Building wheel for spongebob-cli (setup.py) ... done
  Created wheel for spongebob-cli: filename=spongebob_cli-2.0-py3-none-any.whl size=13801 sha256=637419d9be8fcbfc01a7adbcdc094931429dcb682d56115edbdb19e4be20c384
  Stored in directory: /tmp/pip-ephem-wheel-cache-ocvmbz2x/wheels/e4/9f/cb/bc7e5f78b75fd1daae8278aa83122443cc383f17f5e7ee4c79
Successfully built spongebob-cli
Installing collected packages: wcwidth, charset-normalizer, argparse, urllib3, soupsieve, prettytable, idna, certifi, requests, beautifulsoup4, spongebob-cli
Successfully installed argparse-1.4.0 beautifulsoup4-4.11.1 certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 prettytable-3.6.0 requests-2.28.2 soupsieve-2.3.2.post1 spongebob-cli-2.0 urllib3-1.26.14 wcwidth-0.2.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@ea2780667b2b:/# spongebob-cli
+----------------------------------------------------+--------+
|                      Episodes                      | Number |
+----------------------------------------------------+--------+
|                    Help Wanted                     |   0    |
|                    Reef Blower                     |   1    |
|                Tea At The Treedome                 |   2    |
```

can you give me a printout of your env and maybe `python -c "import sys; print('\n'.join(sys.path))"` for your PYTHONPATH?

**Comment by trakBan** [comment]
env:
```
SHELL=/bin/bash
WINDOWID=18874370
COLORTERM=truecolor
I3SOCK=/run/user/1000/i3/ipc-socket.641
XDG_SEAT=seat0
PWD=/home/tb
LOGNAME=tb
XDG_SESSION_TYPE=x11
XAUTHORITY=/run/user/1000/lyxauth
MOTD_SHOWN=pam
HOME=/home/tb
LANG=en_US.UTF-8
LS_COLORS=di=0;35
ALACRITTY_SOCKET=/run/user/1000/Alacritty-:0-1278.sock
XDG_SESSION_CLASS=user
TERM=alacritty
USER=tb
DISPLAY=:0
SHLVL=1
XDG_VTNR=2
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
PS1=\e[0;36m[\u@\h \w]$ \e[0m
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
PATH=/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
ALACRITTY_LOG=/tmp/Alacritty-1278.log
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/tb
ALACRITTY_WINDOW_ID=18874370
_=/sbin/env
```
```
[tb@trak ~]$ python -c "python -c "import sys; print('\n'.join(sys.path))"

/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/tb/.local/lib/python3.10/site-packages
```

**Comment by dashdanw** [comment]
You may be using a different version of pip, can you paste
`pip --version`
and
`pip show spongebob-cli`

**Comment by trakBan** [comment]
```
[tb@archlinux ~/Desktop]$ pip --version
pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
```
```
[tb@archlinux ~/Desktop]$ pip show spongebob-cli
Name: spongebob-cli
Version: 2.0
Summary:
Home-page:
Author:
Author-email:
License:
Location: /home/tb/.local/lib/python3.10/site-packages
Requires: argparse, beautifulsoup4, prettytable, requests
Required-by:
```

**Pull request closed without merging**
