### PR TITLE
Second branche

### PR DESCRIPTION
**Pull request by red-elka**
i added a .gitignore file and a i sorted the apisodes in a table

### CODE REVIEW

**Review by trakBan — CHANGES_REQUESTED** [review]
I like it, however It would be much better if the episode number was on the right side instead of the left side. Also i see no point in making a seperate array for episode_number when there is a counter variable. If you decide to fix these "problems" i will definetly merge this. Thanks for contributing to spongebob-cli!

**Comment by red-elka** [comment]
the .gitignore file is necessary when working with git 
also i added the episode_number cause i need a list not an integer like counter, also i need it outside the for loop so i can  add it easily to table

**Comment by trakBan** [comment]
I didnt realize you couldnt use counter. Can you still change the episode number to the right side?

**Comment by red-elka** [comment]
Yeah of course

**Comment by trakBan** [comment]
Can you please do that? I will merge as soon as you make that change.

**Comment by red-elka** [comment]
i think that's it, right?

**Comment by trakBan** [comment]
Yes it is. Approved!

**Review by trakBan — APPROVED** [review]
Approved

**Pull request merged**
