### PR TITLE
turn func.py into a module

### PR DESCRIPTION
**Pull request by getchoo**
change the name of func.py to Spongebobcli.py, and make a module so it can be installed easier with package managers

### CODE REVIEW

**Comment by getchoo** [comment]
i turned this pr into a patch for the aur package `spongebob-cli-git` (as of [this](https://aur.archlinux.org/cgit/aur.git/commit/?h=spongebob-cli-git&id=4e702511c69e3a0baf3d81d18df425cc3f5e7344) commit), and it works perfectly. by installing `func.py` as a script in `setup.py`, `install()` places it in `/usr/bin` (on linux anyways), which causes the main script to not be able to import any functions from the local file. installing `func.py` as a module puts it in `site-packages`, where it can be imported by the main script.

i also changed the name so it would fit in more with other libraries and couldn't accidentally be imported with other `func` modules.

**Comment by trakBan** [comment]
I really dont want to change the name of func.py. I will have to do testing.

**Comment by getchoo** [comment]
I mean...it can be any name as still installed/imported as a module, you would just need to change the name for the import in `spongebob-cli` and the name of the file in `setup.py`. I just find this to be a better way to manage a local file as it has the same implementation as a local file, but it makes it 100x easier for package maintainers to actually package it as it installs to the python `site-modules` directory instead of `/usr/bin`, where `spongebob-cli` is unable to find it. The `Spongebobcli` name though is just something that I came up with. It can be changed to whatever.

**Comment by trakBan** [comment]
After testing i couldnt get it to work. I want it to make it as easy as possible for you so you can maintane the AUR package. Dont worry i wont forget about this i will try to make it work. Thanks for contributing to spongebob-cli.

**Pull request closed without merging**
